services:
  - type: web
    name: clinic-backend
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn backend.wsgi:application"
    env: python
    region: oregon
    plan: free
    branch: main
    repo: https://github.com/djangolgbtqweb/clinicbackend
    disk:
      name: clinic-sqlite-disk
      mountPath: /persistent
      sizeGB: 1
