# Generated by Django 4.2.17 on 2025-08-13 07:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('outpatient', '0001_initial'),
        ('patients', '0003_appointment_doctor_appointment_purpose_of_visit'),
        ('resource_management', '0008_bed_patients_room_patients_ward_patients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('admitted', 'Admitted'), ('discharged', 'Discharged'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('admitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('admitted_by', models.CharField(blank=True, max_length=200, null=True)),
                ('bed', models.ForeignKey(blank=True, help_text='Assigned bed (nullable until assigned)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='resource_management.bed')),
                ('consultation', models.OneToOneField(help_text='Consultation that led to admission', on_delete=django.db.models.deletion.CASCADE, related_name='admission', to='outpatient.consultationrecord')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='patients.patient')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='resource_management.ward')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
