# Generated by Django 4.2.17 on 2025-06-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_leaverequest_rejection_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='role',
            field=models.CharField(choices=[('Doctor - Cardiology', 'Doctor - Cardiology'), ('Doctor - Pediatrics', 'Doctor - Pediatrics'), ('Doctor - Gynecology', 'Doctor - Gynecology'), ('Doctor - General Surgery', 'Doctor - General Surgery'), ('Doctor - Internal Medicine', 'Doctor - Internal Medicine'), ('Nurse - Registered', 'Nurse - Registered'), ('Nurse - Emergency', 'Nurse - Emergency'), ('Nurse - Pediatric', 'Nurse - Pediatric'), ('Nurse - Post-Operative Care', 'Nurse - Post-Operative Care'), ('Nurse - Chronic Care Management', 'Nurse - Chronic Care Management'), ('Lab Technician - Hematology', 'Lab Technician - Hematology'), ('Lab Technician - Microbiology', 'Lab Technician - Microbiology'), ('Lab Technician - Biochemistry', 'Lab Technician - Biochemistry'), ('Lab Technician - Molecular Diagnostics', 'Lab Technician - Molecular Diagnostics'), ('Mental Health - Trauma Therapy', 'Mental Health - Trauma Therapy'), ('Mental Health - Adolescent Counseling', 'Mental Health - Adolescent Counseling'), ('Mental Health - CBT', 'Mental Health - CBT'), ('Mental Health - Stress & Anxiety', 'Mental Health - Stress & Anxiety'), ('Dentist - Orthodontics', 'Dentist - Orthodontics'), ('Dentist - Cosmetic', 'Dentist - Cosmetic'), ('Dentist - Oral Surgery', 'Dentist - Oral Surgery'), ('Dentist - Pediatric', 'Dentist - Pediatric'), ('Therapist - Physical Therapy', 'Therapist - Physical Therapy'), ('Therapist - Massage Therapy', 'Therapist - Massage Therapy'), ('Therapist - Rehabilitation', 'Therapist - Rehabilitation'), ('Therapist - Pain Management', 'Therapist - Pain Management'), ('Nutritionist - Diabetic Diets', 'Nutritionist - Diabetic Diets'), ('Nutritionist - Pediatric Nutrition', 'Nutritionist - Pediatric Nutrition'), ('Nutritionist - Weight Management', 'Nutritionist - Weight Management'), ('Nutritionist - Clinical Meal Planning', 'Nutritionist - Clinical Meal Planning')], max_length=100),
        ),
    ]
