# Generated by Django 4.2.20 on 2025-06-02 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0003_alter_staffmember_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='pin',
            field=models.CharField(blank=True, help_text='4-digit numeric PIN for staff login (can be blank initially)', max_length=4, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
