# Generated by Django 4.2.17 on 2025-08-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_alter_staffmember_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dutyroster',
            name='shift_time',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'afternoon'), ('Weeekend', 'Weekend'), ('Holidays', 'Holidays'), ('Evening', 'Evening'), ('Night', 'Night')], max_length=50),
        ),
    ]
