# Generated by Django 4.2.17 on 2025-08-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_alter_dutyroster_shift_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dutyroster',
            name='shift_time',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Weekend', 'Weekend'), ('Holidays', 'Holidays'), ('Evening', 'Evening'), ('Night', 'Night')], max_length=50),
        ),
    ]
