# Generated by Django 4.2.20 on 2025-04-18 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ordered', 'Ordered'), ('sample_collected', 'Sample Collected'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='ordered', max_length=20)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='SampleTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_collected_date', models.DateTimeField(blank=True, null=True)),
                ('sample_received_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('collected', 'Collected'), ('in_lab', 'In Lab'), ('processed', 'Processed')], default='pending', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('lab_test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sample', to='laboratory.labtest')),
            ],
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_file', models.FileField(upload_to='lab_results/')),
                ('result_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('lab_test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='laboratory.labtest')),
            ],
        ),
    ]
