# Generated by Django 4.2.17 on 2025-05-18 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomassignment',
            options={'ordering': ['date', 'time_slot']},
        ),
        migrations.AlterUniqueTogether(
            name='roomassignment',
            unique_together={('room', 'date', 'time_slot')},
        ),
    ]
