# Generated by Django 4.2.20 on 2025-05-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_management', '0002_alter_roomassignment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='used_in',
            field=models.CharField(choices=[('minor', 'Minor Theater'), ('resource', 'Resource Management')], default='resource', max_length=50),
        ),
    ]
