# Generated by Django 4.2.20 on 2025-05-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_management', '0003_equipment_used_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='uantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
