# Generated by Django 4.2.20 on 2025-05-18 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource_management', '0004_equipment_uantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='uantity',
            new_name='quantity',
        ),
    ]
