# Generated by Django 4.2.17 on 2025-08-12 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource_management', '0006_equipment_condition_equipment_last_checked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. General Ward A', max_length=200)),
                ('ward_type', models.CharField(choices=[('ICU', 'ICU'), ('HDU', 'HDU / Step-down'), ('GENERAL', 'General / Medical'), ('SURGICAL', 'Surgical'), ('MATERNITY', 'Maternity'), ('NICU', 'NICU'), ('PEDIATRIC', 'Pediatric'), ('ISOLATION', 'Isolation'), ('PSYCHIATRIC', 'Psychiatric'), ('BURN', 'Burn Unit'), ('PACU', 'PACU / Recovery'), ('CONSULT', 'Consultation / Clinic'), ('PROCEDURE', 'Procedure Room'), ('TRIAGE', 'Triage / Observation'), ('DIALYSIS', 'Dialysis Station'), ('IMAGING', 'Imaging / Radiology'), ('PHARMACY', 'Pharmacy Area'), ('SUPPORT', 'Support / Admin')], max_length=30)),
                ('capacity', models.PositiveIntegerField(default=0, help_text='Number of beds (0 for non-bed areas)')),
                ('isolation', models.BooleanField(default=False)),
                ('negative_pressure', models.BooleanField(default=False)),
                ('nursing_station', models.CharField(blank=True, max_length=200, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['ward_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. General-01 or Bed 01', max_length=100)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('cleaning', 'Cleaning'), ('maintenance', 'Maintenance')], default='available', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='resource_management.ward')),
            ],
            options={
                'ordering': ['ward', 'label'],
                'unique_together': {('ward', 'label')},
            },
        ),
    ]
