# Generated by Django 4.2.17 on 2025-08-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_appointment_doctor_appointment_purpose_of_visit'),
        ('resource_management', '0007_ward_bed'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='patients',
            field=models.ManyToManyField(blank=True, related_name='beds', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='room',
            name='patients',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='ward',
            name='patients',
            field=models.ManyToManyField(blank=True, related_name='wards', to='patients.patient'),
        ),
    ]
