# Generated by Django 4.2.17 on 2025-05-26 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_appointment_doctor_appointment_purpose_of_visit'),
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietaryassessment',
            name='patient_name',
        ),
        migrations.AddField(
            model_name='dietaryassessment',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
    ]
