# Generated by Django 4.2.20 on 2025-05-26 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_appointment_doctor_appointment_purpose_of_visit'),
        ('nutrition', '0003_remove_mealplan_patient_name_mealplan_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplementprescription',
            name='patient_name',
        ),
        migrations.AddField(
            model_name='supplementprescription',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplements', to='patients.patient'),
        ),
    ]
