# Generated by Django 4.2.17 on 2025-05-26 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0006_remove_progressmonitor_patient_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressmonitor',
            name='patient_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
