# Generated by Django 4.2.17 on 2025-05-26 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_appointment_doctor_appointment_purpose_of_visit'),
        ('nutrition', '0007_progressmonitor_patient_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progressmonitor',
            name='patient_name',
        ),
        migrations.AlterField(
            model_name='progressmonitor',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='patients.patient'),
        ),
    ]
