# Generated by Django 4.2.20 on 2025-04-22 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycase',
            name='condition',
            field=models.CharField(choices=[('Critical', 'Critical'), ('Stable', 'Stable'), ('Improving', 'Improving'), ('Worsening', 'Worsening')], default='Critical', max_length=50),
        ),
    ]
