# Generated by Django 4.2.20 on 2025-05-15 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        ('emergency', '0002_emergencycase_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencycase',
            name='patient_name',
        ),
        migrations.AddField(
            model_name='emergencycase',
            name='patient',
            field=models.ForeignKey(default=18, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_cases', to='patients.patient'),
            preserve_default=False,
        ),
    ]
