# Generated by Django 4.2.20 on 2025-05-17 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0003_remove_emergencycase_patient_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='emergency_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='emergency.emergencycase'),
        ),
        migrations.AlterField(
            model_name='triagelog',
            name='emergency_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triage_logs', to='emergency.emergencycase'),
        ),
    ]
