# Generated by Django 4.2.17 on 2025-08-11 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_staffmember_pin_staffmember_user'),
        ('emergency', '0004_alter_referral_emergency_case_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_referrals_made', to='staff.staffmember'),
        ),
    ]
