# Generated by Django 4.2.20 on 2025-04-18 21:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consulted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('doctor_name', models.CharField(max_length=200)),
                ('symptoms', models.TextField()),
                ('diagnosis', models.TextField()),
                ('prescriptions', models.TextField(blank=True, help_text='Medication or treatment plan.', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Consultation Record',
                'verbose_name_plural': 'Consultation Records',
                'ordering': ['-consulted_at'],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referred_to', models.CharField(help_text='Specialist or facility referred to.', max_length=200)),
                ('reason', models.TextField(help_text='Reason for referral.')),
                ('referred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='outpatient.consultationrecord')),
            ],
            options={
                'verbose_name': 'Referral',
                'verbose_name_plural': 'Referrals',
                'ordering': ['-referred_at'],
            },
        ),
        migrations.CreateModel(
            name='QueueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrived_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('in_consultation', 'In Consultation'), ('completed', 'Completed'), ('no_show', 'No Show')], default='waiting', max_length=20)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Lower numbers = higher priority')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Queue Entry',
                'verbose_name_plural': 'Queue Entries',
                'ordering': ['status', 'priority', 'arrived_at'],
            },
        ),
        migrations.AddField(
            model_name='consultationrecord',
            name='queue_entry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='outpatient.queueentry'),
        ),
    ]
