# Generated by Django 4.2.17 on 2025-08-13 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_staffmember_pin_staffmember_user'),
        ('outpatient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referrals_made', to='staff.staffmember'),
        ),
    ]
