# Generated by Django 4.2.20 on 2025-04-18 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_type', models.CharField(choices=[('Hypertension', 'Hypertension'), ('Diabetes', 'Diabetes'), ('Asthma', 'Asthma')], max_length=50)),
                ('diagnosis_date', models.DateField()),
                ('treatment_plan', models.TextField()),
                ('status', models.CharField(choices=[('Stable', 'Stable'), ('Unstable', 'Unstable')], max_length=50)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_up_date', models.DateField()),
                ('notes', models.TextField()),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chronic_disease_management.disease')),
            ],
        ),
    ]
