# Generated by Django 4.2.20 on 2025-04-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronic_disease_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='disease_type',
            field=models.CharField(choices=[('Hypertension', 'Hypertension'), ('Diabetes Mellitus', 'Diabetes Mellitus'), ('Asthma', 'Asthma'), ('COPD', 'Chronic Obstructive Pulmonary Disease'), ('CKD', 'Chronic Kidney Disease'), ('CAD', 'Coronary Artery Disease'), ('Heart Failure', 'Heart Failure'), ('Hyperlipidemia', 'Hyperlipidemia'), ('Osteoarthritis', 'Osteoarthritis'), ('Rheumatoid Arthritis', 'Rheumatoid Arthritis'), ('Depression', 'Depression'), ('Anxiety Disorder', 'Anxiety Disorder'), ('Hypothyroidism', 'Hypothyroidism'), ('Hyperthyroidism', 'Hyperthyroidism'), ('GERD', 'Gastroesophageal Reflux Disease'), ('Epilepsy', 'Epilepsy'), ('Parkinson’s Disease', 'Parkinson’s Disease'), ('Dementia', 'Dementia'), ('HIV', 'HIV/AIDS'), ('Stroke', 'Stroke'), ('Obesity', 'Obesity'), ('Chronic Liver Disease', 'Chronic Liver Disease'), ('Anemia', 'Anemia')], max_length=50),
        ),
    ]
