# Generated by Django 4.2.20 on 2025-05-21 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_leaverequest_rejection_reason'),
        ('patients', '0002_medicalrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_appointments', to='staff.staffmember'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='purpose_of_visit',
            field=models.CharField(default=1, help_text='Brief reason or description for the appointment.', max_length=255),
            preserve_default=False,
        ),
    ]
