# Generated by Django 4.2.20 on 2025-04-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_communication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='reference',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
