# Generated by Django 4.2.20 on 2025-04-18 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounselingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counselor', models.CharField(max_length=255)),
                ('session_date', models.DateTimeField()),
                ('session_notes', models.TextField(blank=True)),
                ('session_type', models.CharField(choices=[('mental_health', 'Mental Health'), ('health_education', 'Health Education')], max_length=100)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counseling_sessions', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PrivateNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counselor', models.CharField(max_length=255)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_notes', to='counseling.counselingsession')),
            ],
        ),
        migrations.CreateModel(
            name='HealthEducationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_covered', models.CharField(max_length=255)),
                ('log_notes', models.TextField(blank=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_date', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_education_logs', to='counseling.counselingsession')),
            ],
        ),
        migrations.CreateModel(
            name='FollowUpReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_date', models.DateTimeField()),
                ('reminder_notes', models.TextField(blank=True)),
                ('counseling_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_reminders', to='counseling.counselingsession')),
            ],
        ),
    ]
