# Generated by Django 4.2.17 on 2025-07-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatenote',
            name='counselor_pin',
            field=models.CharField(blank=True, help_text='4‑digit PIN the counselor entered', max_length=10, null=True),
        ),
    ]
