# Generated by Django 4.2.20 on 2025-04-18 21:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=255)),
                ('vaccine_date', models.DateField()),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending')], max_length=20)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='maternal_child_health.patient')),
            ],
        ),
        migrations.CreateModel(
            name='GrowthMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(default=django.utils.timezone.now)),
                ('height', models.FloatField(help_text='Height in cm')),
                ('weight', models.FloatField(help_text='Weight in kg')),
                ('head_circumference', models.FloatField(help_text='Head circumference in cm')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_monitoring', to='maternal_child_health.patient')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyPlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('Contraceptive', 'Contraceptive'), ('Consultation', 'Consultation')], max_length=100)),
                ('service_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('details', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_planning', to='maternal_child_health.patient')),
            ],
        ),
        migrations.CreateModel(
            name='AntenatalPostnatalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('stage', models.CharField(choices=[('Antenatal', 'Antenatal'), ('Postnatal', 'Postnatal')], max_length=50)),
                ('consultation_notes', models.TextField()),
                ('health_status', models.CharField(choices=[('Normal', 'Normal'), ('At Risk', 'At Risk')], max_length=100)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='maternal_child_health.patient')),
            ],
        ),
    ]
