# Generated by Django 4.2.20 on 2025-05-13 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        ('maternal_child_health', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antenatalpostnatalrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='patients.patient'),
        ),
    ]
