# Generated by Django 4.2.20 on 2025-05-14 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        ('maternal_child_health', '0002_alter_antenatalpostnatalrecord_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='patients.patient'),
        ),
    ]
