# Generated by Django 4.2.20 on 2025-05-14 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        ('maternal_child_health', '0004_alter_growthmonitoring_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyplanning',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_planning', to='patients.patient'),
        ),
    ]
